/*
 * MOCK DATA — DEVELOPMENT PLACEHOLDER ONLY.
 * Every record below is invented for layout/testing purposes and does not represent
 * a real person. Replace entirely with genuine roster records (routed through a
 * private application/onboarding process) before this site goes live.
 * No photographs are used for placeholder "portraits" — cards render a gradient
 * swatch + initials instead, so nothing here can be mistaken for a real model.
 */
window.PHOTOCZARO_MODELS = [
  {
    slug: "amara-hassan",
    name: "Amara H.",
    status: "active",
    categories: ["women"],
    subcategories: ["editorial-fashion", "commercial"],
    newFace: false,
    featured: true,
    location: "Dubai, UAE",
    height: "177 cm",
    measurements: "81-61-88 cm",
    hair: "Black",
    eyes: "Brown",
    languages: ["English", "Arabic"],
    skills: ["Runway", "Editorial", "Swimwear"],
    displayOrder: 1,
    swatch: ["#2b2621", "#14120f"],
    seoTitle: "Amara H. — Photoczaro Models Dubai",
    seoDescription: "Amara H., UAE-based editorial and commercial model available for booking through Photoczaro.",
  },
  {
    slug: "layla-novak",
    name: "Layla N.",
    status: "active",
    categories: ["women"],
    subcategories: ["commercial", "beauty"],
    newFace: true,
    featured: true,
    location: "Abu Dhabi, UAE",
    height: "172 cm",
    measurements: "84-64-90 cm",
    hair: "Blonde",
    eyes: "Blue",
    languages: ["English", "Russian"],
    skills: ["Beauty", "Commercial", "Product"],
    displayOrder: 2,
    swatch: ["#221f1a", "#100e0b"],
    seoTitle: "Layla N. — Photoczaro Models Dubai",
    seoDescription: "Layla N., UAE-based new-face model available for beauty and commercial booking through Photoczaro.",
  },
  {
    slug: "omar-farouk",
    name: "Omar F.",
    status: "active",
    categories: ["men"],
    subcategories: ["commercial", "fitness"],
    newFace: false,
    featured: true,
    location: "Dubai, UAE",
    height: "186 cm",
    measurements: "Chest 98 / Waist 81 cm",
    hair: "Black",
    eyes: "Brown",
    languages: ["English", "Arabic", "French"],
    skills: ["Commercial", "Fitness", "Lifestyle"],
    displayOrder: 3,
    swatch: ["#26221d", "#131110"],
    seoTitle: "Omar F. — Photoczaro Models Dubai",
    seoDescription: "Omar F., UAE-based commercial and fitness model available for booking through Photoczaro.",
  },
  {
    slug: "sofia-marchetti",
    name: "Sofia M.",
    status: "active",
    categories: ["women"],
    subcategories: ["editorial-fashion"],
    newFace: false,
    featured: false,
    location: "Dubai, UAE",
    height: "179 cm",
    measurements: "80-60-87 cm",
    hair: "Brown",
    eyes: "Green",
    languages: ["English", "Italian"],
    skills: ["Editorial", "Runway", "Fashion film"],
    displayOrder: 4,
    swatch: ["#25201a", "#121009"],
    seoTitle: "Sofia M. — Photoczaro Models Dubai",
    seoDescription: "Sofia M., UAE-based editorial and fashion model available for booking through Photoczaro.",
  },
  {
    slug: "yusuf-al-rashid",
    name: "Yusuf A.",
    status: "active",
    categories: ["men"],
    subcategories: ["editorial-fashion"],
    newFace: true,
    featured: false,
    location: "Sharjah, UAE",
    height: "189 cm",
    measurements: "Chest 96 / Waist 79 cm",
    hair: "Black",
    eyes: "Dark brown",
    languages: ["English", "Arabic"],
    skills: ["Editorial", "Runway"],
    displayOrder: 5,
    swatch: ["#211d1b", "#100e0d"],
    seoTitle: "Yusuf A. — Photoczaro Models Dubai",
    seoDescription: "Yusuf A., UAE-based new-face editorial model available for booking through Photoczaro.",
  },
  {
    slug: "elena-petrova",
    name: "Elena P.",
    status: "active",
    categories: ["women"],
    subcategories: ["commercial", "beauty"],
    newFace: false,
    featured: false,
    location: "Dubai, UAE",
    height: "170 cm",
    measurements: "83-63-89 cm",
    hair: "Auburn",
    eyes: "Hazel",
    languages: ["English", "Russian"],
    skills: ["Beauty", "Commercial", "Hand model"],
    displayOrder: 6,
    swatch: ["#241f19", "#110f0a"],
    seoTitle: "Elena P. — Photoczaro Models Dubai",
    seoDescription: "Elena P., UAE-based commercial and beauty model available for booking through Photoczaro.",
  },
  {
    slug: "khalid-mansour",
    name: "Khalid M.",
    status: "active",
    categories: ["men"],
    subcategories: ["commercial"],
    newFace: false,
    featured: false,
    location: "Dubai, UAE",
    height: "183 cm",
    measurements: "Chest 100 / Waist 84 cm",
    hair: "Black",
    eyes: "Brown",
    languages: ["English", "Arabic"],
    skills: ["Commercial", "Corporate", "Lifestyle"],
    displayOrder: 7,
    swatch: ["#231f1c", "#110f0d"],
    seoTitle: "Khalid M. — Photoczaro Models Dubai",
    seoDescription: "Khalid M., UAE-based commercial model available for booking through Photoczaro.",
  },
  {
    slug: "noor-abdullah",
    name: "Noor A.",
    status: "active",
    categories: ["women"],
    subcategories: ["editorial-fashion", "beauty"],
    newFace: true,
    featured: true,
    location: "Dubai, UAE",
    height: "175 cm",
    measurements: "82-62-89 cm",
    hair: "Black",
    eyes: "Brown",
    languages: ["English", "Arabic"],
    skills: ["Editorial", "Beauty", "Runway"],
    displayOrder: 8,
    swatch: ["#221e1a", "#100e0c"],
    seoTitle: "Noor A. — Photoczaro Models Dubai",
    seoDescription: "Noor A., UAE-based new-face editorial and beauty model available for booking through Photoczaro.",
  },
];

window.PHOTOCZARO_CATEGORY_LABELS = {
  women: "Women",
  men: "Men",
};
window.PHOTOCZARO_SUBCATEGORY_LABELS = {
  commercial: "Commercial",
  "editorial-fashion": "Editorial / Fashion",
  beauty: "Beauty",
  fitness: "Fitness",
};
